### ISSUE TITLE
Groups not read from LDAP

### ISSUE THREAD

**Issue by vranki** [Kipjr/ldap_login#20]
Not sure if related to issue #3 .

I managed to get user binding to work and LDAP users can login to piwigo.

Problem is the groups. I've set the group DN as:
cn=admin,ou=groups,dc=example,dc=com

We have users that belong to admin group and I'd like to provide them with admin access to piwigo. LDAP server admin is also a user named admin.

After login the plugin seems to read the group members properly, for each member there is log line:
[check_ldap_group_membership]> Test user = user?
And when the user matches:
[check_ldap_group_membership]> memberUid matches user

The result is that user is created in piwigo, but it doesn't have a group assigned so nobody can do anything. I assume LDAP plugin should create the admin group to piwigo when user in the group logs in for the first time.

I suppose I'm doing something wrong but what it might be?

**Comment by Kipjr** [comment]
Hi,

No. You're not doing anything wrong. This plugin provides access to an AD/OpenAD user to Piwigo. It can use groups to filter the security groups, however that is the only thing its does. Currently I'm not able to implement this feature due to some time-consuming personal stuff.
________________________________
Van: Ville Ranki <notifications@github.com>
Verzonden: woensdag 6 februari 2019 16:50
Aan: VSLCatena/ldap_login
CC: Subscribed
Onderwerp: [VSLCatena/ldap_login] Groups not read from LDAP (#20)


Not sure if related to issue #3<https://github.com/VSLCatena/ldap_login/issues/3> .

I managed to get user binding to work and LDAP users can login to piwigo.

Problem is the groups. I've set the group DN as:
cn=admin,ou=groups,dc=example,dc=com

We have users that belong to admin group and I'd like to provide them with admin access to piwigo. LDAP server admin is also a user named admin.

After login the plugin seems to read the group members properly, for each member there is log line:
[check_ldap_group_membership]> Test user = user?
And when the user matches:
[check_ldap_group_membership]> memberUid matches user

The result is that user is created in piwigo, but it doesn't have a group assigned so nobody can do anything. I assume LDAP plugin should create the admin group to piwigo when user in the group logs in for the first time.

I suppose I'm doing something wrong but what it might be?

**Comment by Kipjr** [comment]
The piwigo admin user has all access to do anything. Secondly, I just fixed the webmaster / administrator permissions using 37802bb4dbf489b3d93cb785f2c34c993d3252be
