### ISSUE TITLE
LDAP extension not loaded

### ISSUE THREAD

**Issue by LetArch** [Kipjr/ldap_login#23]
Not work extenstion for piwigo.

Piwigo 2.10.1 
OS: Linux
PHP: 5.6.33-0+deb8u1.netgear1
MySQL: 5.5.62-0+deb8u1
Images library: GD 2.1.1-dev
![Снимок экрана в 2019-10-23 12-13-08](https://user-images.githubusercontent.com/3818210/67372536-1a301d00-f58f-11e9-8e7e-cc72fb2a7440.png)

**Comment by Phil96** [comment]
Same Issue here.

Piwigo 2.10.1 
OS: Linux
PHP: 7.0.33-0+deb9u6
MySQL: 5.5.5-10.1.37-MariaDB-0+deb9u1
Images library: GD 2.2.4
![Anmerkung 2019-10-29 102825](https://user-images.githubusercontent.com/5411084/67754533-e2195600-fa36-11e9-8ff1-5f87ec4a30b7.jpg)

**Comment by Kipjr** [comment]
Hi. Sorry for the delay. 
Have you installed php-ldap (via "apt-get install php-ldap")
And the first time you'll get these notice messages about the cars, it should disappear after the first save

**Comment by Phil96** [comment]
One problem solved, by the way thank you :D But i´ve got another problem now. After i set up the ldap plugin i wanted to try with a test-user and this is what happens when i try to login with it. Do you have a clue what my problem could be?

![Anmerkung 2019-11-19 201102](https://user-images.githubusercontent.com/5411084/69177902-c3bfeb00-0b08-11ea-8a78-41a3785f29d8.jpg)
